# Generated by Django 2.1.2 on 2019-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICTapp', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
