# Generated by Django 2.1.2 on 2019-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICTapp', '0006_specialty_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='perspectives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='tasks',
            field=models.TextField(blank=True),
        ),
    ]
